Expanded post and update methods, now the main photo of posts or pigs can be changed
the-nepodarok/pigs pull request #14
Opened 2024-05-07 16:25 UTC by whatevernumber

2024-05-09 13:41 UTC, the-nepodarok requested changes
Ну и camelCase. Я сам тоже пройдусь по своему коду, чтобы исправить

2024-05-09 13:41 UTC, the-nepodarok commented on models/EntityWithPhotos.php
> +//        try {
Хорошо, можешь убрать закомментированный код

2024-05-09 13:41 UTC, the-nepodarok commented on models/EntityWithPhotos.php
> +    public function changePhotoOrder($main_photo_index): void
Переделай в camelCase. Я сам не везде его придерживался, но не нужно следовать моему плохому примеру

2024-05-09 13:41 UTC, the-nepodarok commented on models/EntityWithPhotos.php
> +        $main = ArrayHelper::remove($photos, $main_photo_index);
mainPhoto

2024-05-09 13:41 UTC, the-nepodarok commented on controllers/PigsController.php
> +                    $pig->refresh();
Возможно, делать рефреш имеет смысл, только если есть difference?

2024-05-09 13:41 UTC, the-nepodarok commented on controllers/PigsController.php
> +                    foreach ($current_photos as $photo) {
Советую попробовать видоизменить текущий метод handlePhotos таким образом, чтобы действия 106-108 производились в нём, а проверку из него вынести в контроллер. Пусть называется attachPhotos и принимает массив (т.е. убрать жёсткую привязку к files внутри него)

2024-05-09 13:41 UTC, the-nepodarok commented on controllers/ArticleController.php
> +                    if (isset($formData['main_photo_name']) || isset($formData['main_photo_index'])) {
Если код повторяется, то имеет смысл вынести его в метод общей модели. Пусть называется rearrange/selectMainPhoto и вызывается при этих же условиях. Уточни, поддерживает ли наша версия PHP named arguments, и если поддерживает, то рассмотри вариант их использования: метод принимает один из двух параметров и действует в зависимости от параметра (либо index, либо name)

2024-05-09 13:44 UTC, the-nepodarok commented on controllers/ArticleController.php
> +                    if (isset($formData['main_photo_name']) || isset($formData['main_photo_index'])) {
Возвращать метод будет массив, который можно тут же передать в attachPhotos

2024-05-09 13:46 UTC, the-nepodarok commented on controllers/ArticleController.php
> +                    } elseif ($article->files) {
С переработанным методом attachPhotos можно будет собирать массив из всех фото и прикреплять всё одним вызовом вместо нескольких

2024-05-10 12:35 UTC, whatevernumber commented on controllers/PigsController.php
> +                    foreach ($current_photos as $photo) {
Скорее всего не получится. Этот метод должен записывать новые фотографии и после создавать связь.
Перезапись же старых выполняется без сохранения на диск, просто повторной привязкой. Переименую этот метод в handleNewPhotos и создам отдельный метод исключительно для привязки старых фотографий

2024-05-10 13:56 UTC, the-nepodarok commented on models/EntityWithPhotos.php
> +     * @param array $old_photos
oldPhotos

2024-05-10 14:21 UTC, the-nepodarok approved these changes

2024-05-10 14:22 UTC, merged